### ISSUE TITLE
terracotta-parent should be published publicly

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-parent#5]
Publish this pom publicly using cloudbees.

**Comment by ljacomet** [comment]
This is already the case, just not on Maven Central but on the Terracotta release repository.

You need to add the following to a Maven project to be able to access it:
```xml
<repositories>
  <repository>
    <id>terracotta-snapshots</id>
    <url>http://www.terracotta.org/download/reflector/snapshots</url>
  </repository>
  <repository>
    <id>terracotta-releases</id>
    <url>http://www.terracotta.org/download/reflector/releases</url>
  </repository>
</repositories>
```

**Comment by myronkscott** [comment]
Should tc-apis and tc-core change to 5.0-SNAPSHOT or should there be a release of a stable version first?

**Comment by ljacomet** [comment]
I prefer sticking with depending on released version.
I was thinking of releasing a 5.0.0.aplha2 once issue #6 about UTF-8 was resolved.

Then if we make good progress and see this is stable, we will release a 5.0.0 at some point.
